// Query TypeMap
import '@sanity/client'

/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: src/sanity/schema.json
export type StepList = {
	_type: 'step-list'
	attributes?: ModuleAttributes
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	steps?: Array<{
		content?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		_type: 'step'
		_key: string
	}>
	enableSchema?: boolean
}

export type ModuleAttributes = {
	_type: 'module-attributes'
	uid?: string
	hidden?: boolean
}

export type StatList = {
	_type: 'stat-list'
	attributes?: ModuleAttributes
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	stats?: Array<{
		value?: string
		suffix?: string
		content?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		_type: 'stat'
		_key: string
	}>
}

export type SearchModule = {
	_type: 'search-module'
	overline?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	scope?: 'all' | 'pages' | 'blog posts'
}

export type SanityImageAssetReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type Prose = {
	_type: 'prose'
	attributes?: ModuleAttributes
	content?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				figcaption?: Array<{
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?: 'normal'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
				}>
				_type: 'image'
				_key: string
		  }
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
	>
	tableOfContents?: 'left' | 'right'
}

export type SanityImageCrop = {
	_type: 'sanity.imageCrop'
	top?: number
	bottom?: number
	left?: number
	right?: number
}

export type SanityImageHotspot = {
	_type: 'sanity.imageHotspot'
	x?: number
	y?: number
	height?: number
	width?: number
}

export type HeroSplit = {
	_type: 'hero.split'
	attributes?: ModuleAttributes
	overline?: string
	content?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	image?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		loading?: 'lazy' | 'eager'
		onRight?: boolean
		afterContent?: boolean
		_type: 'image'
	}
}

export type CustomHtml = {
	_type: 'custom-html'
	attributes?: ModuleAttributes
	className?: string
	html?: Code
	css?: Code
}

export type CardList = {
	_type: 'card-list'
	attributes?: ModuleAttributes
	overline?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	cards?: Array<{
		image?: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		icon?: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		content?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		ctas?: Array<
			{
				_key: string
			} & Cta
		>
		_type: 'card'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	columns?: number
}

export type Callout = {
	_type: 'callout'
	attributes?: ModuleAttributes
	overline?: string
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
}

export type Breadcrumbs = {
	_type: 'breadcrumbs'
	structuredDataOnly?: boolean
	crumbs?: Array<
		{
			_key: string
		} & Link
	>
}

export type BlogPostList = {
	_type: 'blog-post-list'
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	limit?: number
}

export type BlogPostContent = {
	_type: 'blog-post-content'
	attributes?: ModuleAttributes
	tableOfContents?: 'left' | 'right'
}

export type BlogIndex = {
	_type: 'blog-index'
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	postsPerPage?: number
}

export type AccordionList = {
	_type: 'accordion-list'
	attributes?: ModuleAttributes
	intro?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
		listItem?: 'bullet' | 'number'
		markDefs?: Array<{
			href?: string
			_type: 'link'
			_key: string
		}>
		level?: number
		_type: 'block'
		_key: string
	}>
	ctas?: Array<
		{
			_key: string
		} & Cta
	>
	accordions?: Array<{
		summary?: string
		content?: Array<{
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
			listItem?: 'bullet' | 'number'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
		}>
		open?: boolean
		_type: 'accordion'
		_key: string
	}>
	exclusive?: boolean
	enableSchema?: boolean
	layout?: 'vertical' | 'horizontal'
}

export type Seo = {
	_type: 'seo'
	metaTitle?: string
	metaDescription?: string
	ogImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
}

export type NavLabel = {
	_type: 'navLabel'
	label?: string
	link?: string
	xDesktop?: number
	yDesktop?: number
	xMobile?: number
	yMobile?: number
}

export type Metadata = {
	_type: 'metadata'
	title?: string
	description?: string
	slug?: Slug
	image?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	noIndex?: boolean
}

export type Megamenu = {
	_type: 'megamenu'
	link?: Link
	items?: Array<
		| ({
				_key: string
		  } & LinkList)
		| ({
				_key: string
		  } & Link)
	>
}

export type HomePageReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'homePage'
}

export type OurHomesPageReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'ourHomesPage'
}

export type AltWayPageReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'altWayPage'
}

export type ExperiencesPageReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'experiencesPage'
}

export type JoinUsPageReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'joinUsPage'
}

export type ContactPageReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'contactPage'
}

export type LegalPageReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'legalPage'
}

export type BlogPostReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'blog.post'
}

export type Link = {
	_type: 'link'
	label?: string
	type?: 'internal' | 'external'
	internal?:
		| HomePageReference
		| OurHomesPageReference
		| AltWayPageReference
		| ExperiencesPageReference
		| JoinUsPageReference
		| ContactPageReference
		| LegalPageReference
		| BlogPostReference
	external?: string
	params?: string
}

export type Location = {
	_type: 'location'
	displayLocation?: string
	distanceFromLandmark?: string
	googleMapsUrl?: string
	lat?: number
	lng?: number
	streetAddress?: string
	addressLocality?: string
	addressRegion?: string
	postalCode?: string
	addressCountry?: string
}

export type LinkList = {
	_type: 'link.list'
	link?: Link
	links?: Array<
		{
			_key: string
		} & Link
	>
}

export type Cta = {
	_type: 'cta'
	link?: Link
	theme?: 'action' | 'action-outline' | 'ghost' | 'link'
}

export type BlockContent = Array<
	| {
			children?: Array<{
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
			}>
			style?: 'normal' | 'h2' | 'h3' | 'blockquote'
			listItem?: 'bullet'
			markDefs?: Array<{
				href?: string
				_type: 'link'
				_key: string
			}>
			level?: number
			_type: 'block'
			_key: string
	  }
	| {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			alt?: string
			_type: 'image'
			_key: string
	  }
>

export type Site = {
	_id: string
	_type: 'site'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	logoImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	logoText?: string
	favicon?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	navCtaLabel?: string
	navCtaLink?: string
	whatsappNumber?: string
	bookDirectLink?: string
	overlayNavLinks?: Array<{
		label?: string
		url?: string
		_key: string
	}>
	menuPhoto?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	contactEmail?: string
	contactPhone?: string
	checkinTime?: string
	checkoutTime?: string
	instagramUrl?: string
	facebookUrl?: string
	linkedinUrl?: string
	youtubeUrl?: string
	footerBrandName?: string
	footerAboutLinks?: Array<{
		label?: string
		url?: string
		_key: string
	}>
	footerPolicyLinks?: Array<{
		label?: string
		url?: string
		_key: string
	}>
	heroBgCircle?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	heroFgCircle?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	heroDecorStars?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	heroDecorFlowers?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	heroDecorStripes?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	formNotificationEmail?: string
	contactFormEmail?: string
	partnerEnquiryEmail?: string
	colours?: {
		primary?: string
		primaryForeground?: string
		accent?: string
		accentForeground?: string
		background?: string
		foreground?: string
		muted?: string
		border?: string
	}
	fonts?: {
		body?: 'geist' | 'inter' | 'dm-sans' | 'plus-jakarta-sans'
		heading?:
			| 'geist'
			| 'inter'
			| 'dm-sans'
			| 'plus-jakarta-sans'
			| 'playfair-display'
			| 'lora'
			| 'libre-baskerville'
			| 'cormorant-garamond'
		mono?: 'jetbrains-mono' | 'space-mono'
	}
	seo?: Seo
	announcement?: {
		enabled?: boolean
		message?: string
		link?: string
	}
}

export type PropertyReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'property'
}

export type Review = {
	_id: string
	_type: 'review'
	_createdAt: string
	_updatedAt: string
	_rev: string
	guestName?: string
	property?: PropertyReference
	guestLocation?: string
	rating?: number
	stayDate?: string
	body?: string
	published?: boolean
	featured?: boolean
	guestPhoto?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
}

export type Redirect = {
	_id: string
	_type: 'redirect'
	_createdAt: string
	_updatedAt: string
	_rev: string
	source?: string
	destination?: Link
}

export type AmenityReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'amenity'
}

export type ExperienceReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'experience'
}

export type Property = {
	_id: string
	_type: 'property'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	slug?: Slug
	status?: 'active' | 'hidden' | 'coming-soon'
	displayOrder?: number
	rentalwisePropertyId?: string
	rentalwiseIdentifier?: string
	tagline?: string
	shortDescription?: string
	cardThumbnail?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	cardAmenities?: string
	showcaseSecondaryImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	showcaseDecorImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	showcaseDecorTop?: string
	showcaseDecorRight?: string
	showcaseDecorWidth?: number
	showcaseDecorHeight?: number
	showcaseDecorRotation?: number
	propertyType?: string
	priceFrom?: string
	heroImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	detailCoverImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	pullQuote?: string
	detailIntroHeading?: string
	detailIntroBody?: string
	description?: BlockContent
	gallery?: Array<{
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
		_key: string
	}>
	gallerySectionQuote?: string
	galleryDecorImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	locationImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	maxGuests?: number
	bedrooms?: number
	bathrooms?: number
	amenities?: Array<
		{
			_key: string
		} & AmenityReference
	>
	houseRulesTeaser?: string
	houseRules?: BlockContent
	amenitiesSectionImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	location?: Location
	locationHeadline?: string
	locationBody?: BlockContent
	locationCta?: {
		label?: string
		url?: string
	}
	highlights?: Array<{
		title?: string
		body?: string
		image?: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			alt?: string
			_type: 'image'
		}
		secondaryImage?: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			alt?: string
			_type: 'image'
		}
		decorImage?: {
			asset?: SanityImageAssetReference
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		}
		_key: string
	}>
	experiences?: Array<
		{
			_key: string
		} & ExperienceReference
	>
	experiencesMaxShown?: number
	experiencesBgImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	menuCta?: {
		label?: string
		url?: string
	}
	faqs?: Array<{
		question?: string
		answer?: BlockContent
		_type: 'faq'
		_key: string
	}>
	causeHeadline?: string
	causeBody?: BlockContent
	causeImages?: Array<{
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
		_key: string
	}>
	reviewsMaxShown?: number
	ctaHeadline?: string
	ctaButtonLabel?: string
	ctaBackground?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	seo?: Seo
}

export type Slug = {
	_type: 'slug'
	current?: string
	source?: string
}

export type OurHomesPage = {
	_id: string
	_type: 'ourHomesPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroHeadline?: string
	heroImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	experiencesCtaBody?: BlockContent
	experiencesCtaLabel?: string
	ctaQuestion?: string
	ctaBackground?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	seo?: Seo
}

export type LegalPage = {
	_id: string
	_type: 'legalPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	displayTitle?: string
	seoTitle?: string
	slug?: Slug
	body?: BlockContent
	backgroundImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	seo?: Seo
}

export type JoinUsPage = {
	_id: string
	_type: 'joinUsPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroHeadline?: string
	pullQuote?: string
	heroImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	bodyParagraph?: string
	bulletPoints?: Array<string>
	formCTAText?: string
	propertyImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	formHeadline?: string
	heroDecorFlower?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	contentDecorImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	formDecorBg?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	seo?: Seo
}

export type HomePage = {
	_id: string
	_type: 'homePage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroHeadline?: string
	heroImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	navLabels?: Array<
		{
			_key: string
		} & NavLabel
	>
	seo?: Seo
}

export type ExperiencesPage = {
	_id: string
	_type: 'experiencesPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroHeadline?: string
	heroBackground?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	cardsMaxShown?: number
	leadingTagline?: string
	supportingTagline?: string
	heroFlower?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	decorBasket?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	decorStars?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	decorDaisy?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	seo?: Seo
}

export type Experience = {
	_id: string
	_type: 'experience'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	slug?: Slug
	description?: string
	image?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	properties?: Array<
		{
			_key: string
		} & PropertyReference
	>
	displayOrder?: number
	seo?: Seo
}

export type ContactPage = {
	_id: string
	_type: 'contactPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	sectionTitle?: string
	phone?: string
	email?: string
	officeCity?: string
	officeAddress?: string
	formHeadline?: string
	formCardHeading?: string
	officeSectionTitle?: string
	followUsSectionTitle?: string
	mobileHeroAsset?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	backgroundCloudAsset?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	sideFlowerAsset?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	seo?: Seo
}

export type BlogPost = {
	_id: string
	_type: 'blog.post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	content?: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'normal'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'blockquote'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				figcaption?: Array<{
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?: 'normal'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
				}>
				_type: 'image'
				_key: string
		  }
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
	>
	publishDate?: string
	metadata?: Metadata
}

export type Code = {
	_type: 'code'
	language?: string
	filename?: string
	code?: string
	highlightedLines?: Array<number>
}

export type Amenity = {
	_id: string
	_type: 'amenity'
	_createdAt: string
	_updatedAt: string
	_rev: string
	name?: string
	icon?: string
}

export type ReviewReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'review'
}

export type AltWayPage = {
	_id: string
	_type: 'altWayPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroHeadline?: string
	heroHeadlineLine2?: string
	heroBackground?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	missionImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	missionDecorImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	missionText?: string
	valuePropHeadline?: string
	valueProps?: Array<{
		title?: string
		body?: string
		_key: string
	}>
	valuePropEditorialImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	valuePropEditorialDecorLeft?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	valuePropEditorialDecorRight?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	valuePropSecondaryImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	promiseText?: string
	promiseCTALabel?: string
	promiseCTAHref?: string
	promiseBackground?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	promiseCTADecorLeft?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	promiseCTADecorRight?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	statsHeadline?: string
	stats?: Array<{
		value?: string
		label?: string
		subtext?: string
		_key: string
	}>
	bottomCTAHeadline?: string
	bottomCTALabel?: string
	bottomCTABackground?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	bottomCTAHref?: string
	reviews?: Array<
		{
			_key: string
		} & ReviewReference
	>
	seo?: Seo
}

export type SanityAssistInstructionTask = {
	_type: 'sanity.assist.instructionTask'
	path?: string
	instructionKey?: string
	started?: string
	updated?: string
	info?: string
}

export type SanityAssistTaskStatus = {
	_type: 'sanity.assist.task.status'
	tasks?: Array<
		{
			_key: string
		} & SanityAssistInstructionTask
	>
}

export type SanityAssistSchemaTypeAnnotations = {
	_type: 'sanity.assist.schemaType.annotations'
	title?: string
	fields?: Array<
		{
			_key: string
		} & SanityAssistSchemaTypeField
	>
}

export type SanityAssistOutputType = {
	_type: 'sanity.assist.output.type'
	type?: string
}

export type SanityAssistOutputField = {
	_type: 'sanity.assist.output.field'
	path?: string
}

export type AssistInstructionContextReference = {
	_ref: string
	_type: 'reference'
	_weak?: boolean
	[internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
	_type: 'sanity.assist.instruction.context'
	reference?: AssistInstructionContextReference
}

export type AssistInstructionContext = {
	_id: string
	_type: 'assist.instruction.context'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	context?: Array<{
		children?: Array<{
			marks?: Array<string>
			text?: string
			_type: 'span'
			_key: string
		}>
		style?: 'normal'
		listItem?: never
		markDefs?: null
		level?: number
		_type: 'block'
		_key: string
	}>
}

export type SanityAssistInstructionUserInput = {
	_type: 'sanity.assist.instruction.userInput'
	message?: string
	description?: string
}

export type SanityAssistInstructionPrompt = Array<{
	children?: Array<
		| {
				marks?: Array<string>
				text?: string
				_type: 'span'
				_key: string
		  }
		| ({
				_key: string
		  } & SanityAssistInstructionFieldRef)
		| ({
				_key: string
		  } & SanityAssistInstructionContext)
		| ({
				_key: string
		  } & SanityAssistInstructionUserInput)
	>
	style?: 'normal'
	listItem?: never
	markDefs?: null
	level?: number
	_type: 'block'
	_key: string
}>

export type SanityAssistInstructionFieldRef = {
	_type: 'sanity.assist.instruction.fieldRef'
	path?: string
}

export type SanityAssistInstruction = {
	_type: 'sanity.assist.instruction'
	prompt?: SanityAssistInstructionPrompt
	icon?: string
	title?: string
	userId?: string
	createdById?: string
	output?: Array<
		| ({
				_key: string
		  } & SanityAssistOutputField)
		| ({
				_key: string
		  } & SanityAssistOutputType)
	>
}

export type SanityAssistSchemaTypeField = {
	_type: 'sanity.assist.schemaType.field'
	path?: string
	instructions?: Array<
		{
			_key: string
		} & SanityAssistInstruction
	>
}

export type SanityImagePaletteSwatch = {
	_type: 'sanity.imagePaletteSwatch'
	background?: string
	foreground?: string
	population?: number
	title?: string
}

export type SanityImagePalette = {
	_type: 'sanity.imagePalette'
	darkMuted?: SanityImagePaletteSwatch
	lightVibrant?: SanityImagePaletteSwatch
	darkVibrant?: SanityImagePaletteSwatch
	vibrant?: SanityImagePaletteSwatch
	dominant?: SanityImagePaletteSwatch
	lightMuted?: SanityImagePaletteSwatch
	muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
	_type: 'sanity.imageDimensions'
	height?: number
	width?: number
	aspectRatio?: number
}

export type SanityImageMetadata = {
	_type: 'sanity.imageMetadata'
	location?: Geopoint
	dimensions?: SanityImageDimensions
	palette?: SanityImagePalette
	lqip?: string
	blurHash?: string
	thumbHash?: string
	hasAlpha?: boolean
	isOpaque?: boolean
}

export type SanityFileAsset = {
	_id: string
	_type: 'sanity.fileAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash?: string
	extension?: string
	mimeType?: string
	size?: number
	assetId?: string
	uploadId?: string
	path?: string
	url?: string
	source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
	_type: 'sanity.assetSourceData'
	name?: string
	id?: string
	url?: string
}

export type SanityImageAsset = {
	_id: string
	_type: 'sanity.imageAsset'
	_createdAt: string
	_updatedAt: string
	_rev: string
	originalFilename?: string
	label?: string
	title?: string
	description?: string
	altText?: string
	sha1hash?: string
	extension?: string
	mimeType?: string
	size?: number
	assetId?: string
	uploadId?: string
	path?: string
	url?: string
	metadata?: SanityImageMetadata
	source?: SanityAssetSourceData
}

export type Geopoint = {
	_type: 'geopoint'
	lat?: number
	lng?: number
	alt?: number
}

export type AllSanitySchemaTypes =
	| StepList
	| ModuleAttributes
	| StatList
	| SearchModule
	| SanityImageAssetReference
	| Prose
	| SanityImageCrop
	| SanityImageHotspot
	| HeroSplit
	| CustomHtml
	| CardList
	| Callout
	| Breadcrumbs
	| BlogPostList
	| BlogPostContent
	| BlogIndex
	| AccordionList
	| Seo
	| NavLabel
	| Metadata
	| Megamenu
	| HomePageReference
	| OurHomesPageReference
	| AltWayPageReference
	| ExperiencesPageReference
	| JoinUsPageReference
	| ContactPageReference
	| LegalPageReference
	| BlogPostReference
	| Link
	| Location
	| LinkList
	| Cta
	| BlockContent
	| Site
	| PropertyReference
	| Review
	| Redirect
	| AmenityReference
	| ExperienceReference
	| Property
	| Slug
	| OurHomesPage
	| LegalPage
	| JoinUsPage
	| HomePage
	| ExperiencesPage
	| Experience
	| ContactPage
	| BlogPost
	| Code
	| Amenity
	| ReviewReference
	| AltWayPage
	| SanityAssistInstructionTask
	| SanityAssistTaskStatus
	| SanityAssistSchemaTypeAnnotations
	| SanityAssistOutputType
	| SanityAssistOutputField
	| AssistInstructionContextReference
	| SanityAssistInstructionContext
	| AssistInstructionContext
	| SanityAssistInstructionUserInput
	| SanityAssistInstructionPrompt
	| SanityAssistInstructionFieldRef
	| SanityAssistInstruction
	| SanityAssistSchemaTypeField
	| SanityImagePaletteSwatch
	| SanityImagePalette
	| SanityImageDimensions
	| SanityImageMetadata
	| SanityFileAsset
	| SanityAssetSourceData
	| SanityImageAsset
	| Geopoint

// Source: src/app/(site)/api/og/route.tsx
// Variable: OG_QUERY
// Query: *[_type == $type && metadata.slug.current == $slug][0]{	'title': coalesce(metadata.title, title),}
export type OG_QUERY_RESULT =
	| {
			title: null
	  }
	| {
			title: string | null
	  }
	| {
			title: string | null
	  }
	| null

// Source: src/app/(site)/blog/[slug]/page.tsx
// Variable: BLOG_POST_QUERY
// Query: *[_type == 'blog.post' && metadata.slug.current == $slug][0]{	...,	content[]{		...,		_type == 'image' => {			...,			asset->		}	},	'contentPlainText': pt::text(content),	'readTime': length(string::split(pt::text(content), ' ')) / 200,	'headings': content[style in ['h2', 'h3', 'h4', 'h5', 'h6']]{		style,		'text': pt::text(@)	},	categories[]->{		title,		slug	},	author->{		name,		image{			...,			asset->		}	}}
export type BLOG_POST_QUERY_RESULT = {
	_id: string
	_type: 'blog.post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	content: Array<
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				_key: string
				_type: 'code'
				language?: string
				filename?: string
				code?: string
				highlightedLines?: Array<number>
		  }
		| {
				_key: string
				_type: 'custom-html'
				attributes?: ModuleAttributes
				className?: string
				html?: Code
				css?: Code
		  }
		| {
				asset: {
					_id: string
					_type: 'sanity.imageAsset'
					_createdAt: string
					_updatedAt: string
					_rev: string
					originalFilename?: string
					label?: string
					title?: string
					description?: string
					altText?: string
					sha1hash?: string
					extension?: string
					mimeType?: string
					size?: number
					assetId?: string
					uploadId?: string
					path?: string
					url?: string
					metadata?: SanityImageMetadata
					source?: SanityAssetSourceData
				} | null
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				figcaption?: Array<{
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?: 'normal'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
				}>
				_type: 'image'
				_key: string
		  }
	> | null
	publishDate?: string
	metadata?: Metadata
	contentPlainText: string
	readTime: number
	headings: Array<{
		style:
			| 'blockquote'
			| 'h1'
			| 'h2'
			| 'h3'
			| 'h4'
			| 'h5'
			| 'h6'
			| 'normal'
			| null
		text: string
	}> | null
	categories: null
	author: null
} | null

// Source: src/app/(site)/blog/rss.xml/route.ts
// Variable: BLOG_RSS_QUERY
// Query: {	'blog': *[_type == 'site'][0]{		"metadata": {			"title": coalesce(seo.metaTitle, title) + " Blog",			"description": seo.metaDescription		}	},	'posts': *[_type == 'blog.post' && metadata.noIndex != true]|order(publishDate desc){		title,		content,		publishDate,		metadata	}}
export type BLOG_RSS_QUERY_RESULT = {
	blog: {
		metadata: {
			title: string | null
			description: string | null
		}
	} | null
	posts: Array<{
		title: string | null
		content: Array<
			| ({
					_key: string
			  } & Code)
			| ({
					_key: string
			  } & CustomHtml)
			| {
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?:
						| 'blockquote'
						| 'h1'
						| 'h2'
						| 'h3'
						| 'h4'
						| 'h5'
						| 'h6'
						| 'normal'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
			  }
			| {
					asset?: SanityImageAssetReference
					media?: unknown
					hotspot?: SanityImageHotspot
					crop?: SanityImageCrop
					alt?: string
					figcaption?: Array<{
						children?: Array<{
							marks?: Array<string>
							text?: string
							_type: 'span'
							_key: string
						}>
						style?: 'normal'
						listItem?: 'bullet' | 'number'
						markDefs?: Array<{
							href?: string
							_type: 'link'
							_key: string
						}>
						level?: number
						_type: 'block'
						_key: string
					}>
					_type: 'image'
					_key: string
			  }
		> | null
		publishDate: string | null
		metadata: Metadata | null
	}>
}

// Source: src/sanity/lib/queries.ts
// Variable: SITE_QUERY
// Query: *[_type == 'site' && _id == 'site'][0]
export type SITE_QUERY_RESULT = {
	_id: 'site'
	_type: 'site'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	logoImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	logoText?: string
	favicon?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	navCtaLabel?: string
	navCtaLink?: string
	whatsappNumber?: string
	bookDirectLink?: string
	overlayNavLinks?: Array<{
		label?: string
		url?: string
		_key: string
	}>
	menuPhoto?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	contactEmail?: string
	contactPhone?: string
	checkinTime?: string
	checkoutTime?: string
	instagramUrl?: string
	facebookUrl?: string
	linkedinUrl?: string
	youtubeUrl?: string
	footerBrandName?: string
	footerAboutLinks?: Array<{
		label?: string
		url?: string
		_key: string
	}>
	footerPolicyLinks?: Array<{
		label?: string
		url?: string
		_key: string
	}>
	heroBgCircle?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	heroFgCircle?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	heroDecorStars?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	heroDecorFlowers?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	heroDecorStripes?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	formNotificationEmail?: string
	contactFormEmail?: string
	partnerEnquiryEmail?: string
	colours?: {
		primary?: string
		primaryForeground?: string
		accent?: string
		accentForeground?: string
		background?: string
		foreground?: string
		muted?: string
		border?: string
	}
	fonts?: {
		body?: 'dm-sans' | 'geist' | 'inter' | 'plus-jakarta-sans'
		heading?:
			| 'cormorant-garamond'
			| 'dm-sans'
			| 'geist'
			| 'inter'
			| 'libre-baskerville'
			| 'lora'
			| 'playfair-display'
			| 'plus-jakarta-sans'
		mono?: 'jetbrains-mono' | 'space-mono'
	}
	seo?: Seo
	announcement?: {
		enabled?: boolean
		message?: string
		link?: string
	}
} | null

// Source: src/sanity/lib/queries.ts
// Variable: HOME_PAGE_QUERY
// Query: *[_type == 'homePage' && _id == 'homePage'][0]{	...,	heroImage { asset->, alt },	navLabels[]{		...,		target->{ _type, "slug": slug.current }	}}
export type HOME_PAGE_QUERY_RESULT = {
	_id: 'homePage'
	_type: 'homePage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroHeadline?: string
	heroImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	navLabels: Array<{
		_key: string
		_type: 'navLabel'
		label?: string
		link?: string
		xDesktop?: number
		yDesktop?: number
		xMobile?: number
		yMobile?: number
		target: null
	}> | null
	seo?: Seo
} | null

// Source: src/sanity/lib/queries.ts
// Variable: OUR_HOMES_PAGE_QUERY
// Query: *[_type == 'ourHomesPage' && _id == 'ourHomesPage'][0]{	heroHeadline,	heroImage { asset->, alt },	ctaQuestion,	experiencesCtaLabel,	ctaBackground { asset->, alt },	seo}
export type OUR_HOMES_PAGE_QUERY_RESULT = {
	heroHeadline: string | null
	heroImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	ctaQuestion: string | null
	experiencesCtaLabel: string | null
	ctaBackground: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	seo: Seo | null
} | null

// Source: src/sanity/lib/queries.ts
// Variable: ALT_WAY_PAGE_QUERY
// Query: *[_type == 'altWayPage' && _id == 'altWayPage'][0]{	...,	heroBackground { asset->, alt },	missionImage { asset->, alt },	missionDecorImage { asset->, alt },	valuePropEditorialImage { asset->, alt },	valuePropEditorialDecorLeft { asset->, alt },	valuePropEditorialDecorRight { asset->, alt },	valuePropSecondaryImage { asset->, alt },	promiseBackground { asset->, alt },	promiseCTADecorLeft { asset->, alt },	promiseCTADecorRight { asset->, alt },	bottomCTABackground { asset->, alt },	reviews[]->{		guestName, rating, body, guestLocation, stayDate,		guestPhoto { asset->, alt },		"propertyTitle": property->title	}}
export type ALT_WAY_PAGE_QUERY_RESULT = {
	_id: 'altWayPage'
	_type: 'altWayPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroHeadline?: string
	heroHeadlineLine2?: string
	heroBackground: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	missionImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	missionDecorImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	missionText?: string
	valuePropHeadline?: string
	valueProps?: Array<{
		title?: string
		body?: string
		_key: string
	}>
	valuePropEditorialImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	valuePropEditorialDecorLeft: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	valuePropEditorialDecorRight: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	valuePropSecondaryImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	promiseText?: string
	promiseCTALabel?: string
	promiseCTAHref?: string
	promiseBackground: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	promiseCTADecorLeft: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	promiseCTADecorRight: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	statsHeadline?: string
	stats?: Array<{
		value?: string
		label?: string
		subtext?: string
		_key: string
	}>
	bottomCTAHeadline?: string
	bottomCTALabel?: string
	bottomCTABackground: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	bottomCTAHref?: string
	reviews: Array<{
		guestName: string | null
		rating: number | null
		body: string | null
		guestLocation: string | null
		stayDate: string | null
		guestPhoto: {
			asset: {
				_id: string
				_type: 'sanity.imageAsset'
				_createdAt: string
				_updatedAt: string
				_rev: string
				originalFilename?: string
				label?: string
				title?: string
				description?: string
				altText?: string
				sha1hash?: string
				extension?: string
				mimeType?: string
				size?: number
				assetId?: string
				uploadId?: string
				path?: string
				url?: string
				metadata?: SanityImageMetadata
				source?: SanityAssetSourceData
			} | null
			alt: string | null
		} | null
		propertyTitle: string | null
	}> | null
	seo?: Seo
} | null

// Source: src/sanity/lib/queries.ts
// Variable: EXPERIENCES_PAGE_QUERY
// Query: *[_type == 'experiencesPage' && _id == 'experiencesPage'][0]{	...,	heroBackground { asset->, alt },	heroFlower { asset->, alt },	decorBasket { asset->, alt },	decorStars { asset->, alt },	decorDaisy { asset->, alt }}
export type EXPERIENCES_PAGE_QUERY_RESULT = {
	_id: 'experiencesPage'
	_type: 'experiencesPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroHeadline?: string
	heroBackground: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	cardsMaxShown?: number
	leadingTagline?: string
	supportingTagline?: string
	heroFlower: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	decorBasket: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	decorStars: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	decorDaisy: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	seo?: Seo
} | null

// Source: src/sanity/lib/queries.ts
// Variable: JOIN_US_PAGE_QUERY
// Query: *[_type == 'joinUsPage' && _id == 'joinUsPage'][0]{	...,	heroImage { asset->, alt },	propertyImage { asset->, alt },	heroDecorFlower { asset-> },	contentDecorImage { asset-> },	formDecorBg { asset-> }}
export type JOIN_US_PAGE_QUERY_RESULT = {
	_id: 'joinUsPage'
	_type: 'joinUsPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroHeadline?: string
	pullQuote?: string
	heroImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	bodyParagraph?: string
	bulletPoints?: Array<string>
	formCTAText?: string
	propertyImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	formHeadline?: string
	heroDecorFlower: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
	} | null
	contentDecorImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
	} | null
	formDecorBg: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
	} | null
	seo?: Seo
} | null

// Source: src/sanity/lib/queries.ts
// Variable: CONTACT_PAGE_QUERY
// Query: *[_type == 'contactPage' && _id == 'contactPage'][0]{	...,	heroImage { asset->, alt },	mobileHeroAsset { asset->, alt },	backgroundCloudAsset { asset->, alt },	sideFlowerAsset { asset->, alt }}
export type CONTACT_PAGE_QUERY_RESULT = {
	_id: 'contactPage'
	_type: 'contactPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	heroImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	sectionTitle?: string
	phone?: string
	email?: string
	officeCity?: string
	officeAddress?: string
	formHeadline?: string
	formCardHeading?: string
	officeSectionTitle?: string
	followUsSectionTitle?: string
	mobileHeroAsset: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	backgroundCloudAsset: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	sideFlowerAsset: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	seo?: Seo
} | null

// Source: src/sanity/lib/queries.ts
// Variable: LEGAL_PAGE_QUERY
// Query: *[_type == 'legalPage' && slug.current == $slug][0]
export type LEGAL_PAGE_QUERY_RESULT = {
	_id: string
	_type: 'legalPage'
	_createdAt: string
	_updatedAt: string
	_rev: string
	displayTitle?: string
	seoTitle?: string
	slug?: Slug
	body?: BlockContent
	backgroundImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	seo?: Seo
} | null

// Source: src/sanity/lib/queries.ts
// Variable: ALL_LEGAL_PAGES_QUERY
// Query: *[_type == 'legalPage' && defined(slug.current)].slug.current
export type ALL_LEGAL_PAGES_QUERY_RESULT = Array<string | null>

// Source: src/sanity/lib/queries.ts
// Variable: ALL_PROPERTIES_QUERY
// Query: *[_type == 'property' && status != 'hidden'] | order(displayOrder asc){	_id,	title,	"slug": slug.current,	tagline,	shortDescription,	cardThumbnail { asset->, alt },	heroImage { asset->, alt },	showcaseSecondaryImage { asset->, alt },	showcaseDecorImage { asset->, alt },	showcaseDecorTop,	showcaseDecorRight,	showcaseDecorWidth,	showcaseDecorHeight,	showcaseDecorRotation,	pullQuote,	locationHeadline,	cardAmenities,	propertyType,	priceFrom,	maxGuests,	bedrooms,	bathrooms,	status,	displayOrder,	rentalwisePropertyId}
export type ALL_PROPERTIES_QUERY_RESULT = Array<{
	_id: string
	title: string | null
	slug: string | null
	tagline: string | null
	shortDescription: string | null
	cardThumbnail: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	heroImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	showcaseSecondaryImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	showcaseDecorImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	showcaseDecorTop: string | null
	showcaseDecorRight: string | null
	showcaseDecorWidth: number | null
	showcaseDecorHeight: number | null
	showcaseDecorRotation: number | null
	pullQuote: string | null
	locationHeadline: string | null
	cardAmenities: string | null
	propertyType: string | null
	priceFrom: string | null
	maxGuests: number | null
	bedrooms: number | null
	bathrooms: number | null
	status: 'active' | 'coming-soon' | 'hidden' | null
	displayOrder: number | null
	rentalwisePropertyId: string | null
}>

// Source: src/sanity/lib/queries.ts
// Variable: PROPERTY_QUERY
// Query: *[_type == 'property' && slug.current == $slug][0]{	...,	heroImage { asset->, alt },	detailCoverImage { asset->, alt },	gallery[]{ asset->, alt },	cardThumbnail { asset->, alt },	amenities[]->{ name, icon },	amenitiesSectionImage { asset->, alt },	experiences[]->{		title,		"slug": slug.current,		description,		image { asset->, alt }	},	experiencesBgImage { asset->, alt, hotspot, crop },	highlights[]{ title, body, image { asset->, alt }, secondaryImage { asset->, alt }, decorImage { asset-> } },	causeImages[]{ asset->, alt },	ctaBackground { asset->, alt },	faqs[]{ question, answer },	location,	"reviews": *[_type=='review' && references(^._id) && published==true] | order(stayDate desc) [0..20]{		guestName, rating, body, guestLocation, stayDate,		guestPhoto { asset->, alt },		"propertyTitle": property->title	}}
export type PROPERTY_QUERY_RESULT = {
	_id: string
	_type: 'property'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	slug?: Slug
	status?: 'active' | 'coming-soon' | 'hidden'
	displayOrder?: number
	rentalwisePropertyId?: string
	rentalwiseIdentifier?: string
	tagline?: string
	shortDescription?: string
	cardThumbnail: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	cardAmenities?: string
	showcaseSecondaryImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	showcaseDecorImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		alt?: string
		_type: 'image'
	}
	showcaseDecorTop?: string
	showcaseDecorRight?: string
	showcaseDecorWidth?: number
	showcaseDecorHeight?: number
	showcaseDecorRotation?: number
	propertyType?: string
	priceFrom?: string
	heroImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	detailCoverImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	pullQuote?: string
	detailIntroHeading?: string
	detailIntroBody?: string
	description?: BlockContent
	gallery: Array<{
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	}> | null
	gallerySectionQuote?: string
	galleryDecorImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	locationImage?: {
		asset?: SanityImageAssetReference
		media?: unknown
		hotspot?: SanityImageHotspot
		crop?: SanityImageCrop
		_type: 'image'
	}
	maxGuests?: number
	bedrooms?: number
	bathrooms?: number
	amenities: Array<{
		name: string | null
		icon: string | null
	}> | null
	houseRulesTeaser?: string
	houseRules?: BlockContent
	amenitiesSectionImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	location: Location | null
	locationHeadline?: string
	locationBody?: BlockContent
	locationCta?: {
		label?: string
		url?: string
	}
	highlights: Array<{
		title: string | null
		body: string | null
		image: {
			asset: {
				_id: string
				_type: 'sanity.imageAsset'
				_createdAt: string
				_updatedAt: string
				_rev: string
				originalFilename?: string
				label?: string
				title?: string
				description?: string
				altText?: string
				sha1hash?: string
				extension?: string
				mimeType?: string
				size?: number
				assetId?: string
				uploadId?: string
				path?: string
				url?: string
				metadata?: SanityImageMetadata
				source?: SanityAssetSourceData
			} | null
			alt: string | null
		} | null
		secondaryImage: {
			asset: {
				_id: string
				_type: 'sanity.imageAsset'
				_createdAt: string
				_updatedAt: string
				_rev: string
				originalFilename?: string
				label?: string
				title?: string
				description?: string
				altText?: string
				sha1hash?: string
				extension?: string
				mimeType?: string
				size?: number
				assetId?: string
				uploadId?: string
				path?: string
				url?: string
				metadata?: SanityImageMetadata
				source?: SanityAssetSourceData
			} | null
			alt: string | null
		} | null
		decorImage: {
			asset: {
				_id: string
				_type: 'sanity.imageAsset'
				_createdAt: string
				_updatedAt: string
				_rev: string
				originalFilename?: string
				label?: string
				title?: string
				description?: string
				altText?: string
				sha1hash?: string
				extension?: string
				mimeType?: string
				size?: number
				assetId?: string
				uploadId?: string
				path?: string
				url?: string
				metadata?: SanityImageMetadata
				source?: SanityAssetSourceData
			} | null
		} | null
	}> | null
	experiences: Array<{
		title: string | null
		slug: string | null
		description: string | null
		image: {
			asset: {
				_id: string
				_type: 'sanity.imageAsset'
				_createdAt: string
				_updatedAt: string
				_rev: string
				originalFilename?: string
				label?: string
				title?: string
				description?: string
				altText?: string
				sha1hash?: string
				extension?: string
				mimeType?: string
				size?: number
				assetId?: string
				uploadId?: string
				path?: string
				url?: string
				metadata?: SanityImageMetadata
				source?: SanityAssetSourceData
			} | null
			alt: string | null
		} | null
	}> | null
	experiencesMaxShown?: number
	experiencesBgImage: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
		hotspot: SanityImageHotspot | null
		crop: SanityImageCrop | null
	} | null
	menuCta?: {
		label?: string
		url?: string
	}
	faqs: Array<{
		question: string | null
		answer: BlockContent | null
	}> | null
	causeHeadline?: string
	causeBody?: BlockContent
	causeImages: Array<{
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	}> | null
	reviewsMaxShown?: number
	ctaHeadline?: string
	ctaButtonLabel?: string
	ctaBackground: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	seo?: Seo
	reviews: Array<{
		guestName: string | null
		rating: number | null
		body: string | null
		guestLocation: string | null
		stayDate: string | null
		guestPhoto: {
			asset: {
				_id: string
				_type: 'sanity.imageAsset'
				_createdAt: string
				_updatedAt: string
				_rev: string
				originalFilename?: string
				label?: string
				title?: string
				description?: string
				altText?: string
				sha1hash?: string
				extension?: string
				mimeType?: string
				size?: number
				assetId?: string
				uploadId?: string
				path?: string
				url?: string
				metadata?: SanityImageMetadata
				source?: SanityAssetSourceData
			} | null
			alt: string | null
		} | null
		propertyTitle: string | null
	}>
} | null

// Source: src/sanity/lib/queries.ts
// Variable: ALL_PROPERTY_SLUGS_QUERY
// Query: *[_type == 'property' && defined(slug.current)].slug.current
export type ALL_PROPERTY_SLUGS_QUERY_RESULT = Array<string | null>

// Source: src/sanity/lib/queries.ts
// Variable: ALL_POSTS_QUERY
// Query: *[_type == 'blog.post'] | order(publishDate desc)
export type ALL_POSTS_QUERY_RESULT = Array<{
	_id: string
	_type: 'blog.post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	content?: Array<
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				figcaption?: Array<{
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?: 'normal'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
				}>
				_type: 'image'
				_key: string
		  }
	>
	publishDate?: string
	metadata?: Metadata
}>

// Source: src/sanity/lib/queries.ts
// Variable: POST_BY_SLUG_QUERY
// Query: *[_type == 'blog.post' && metadata.slug.current == $slug][0]
export type POST_BY_SLUG_QUERY_RESULT = {
	_id: string
	_type: 'blog.post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	content?: Array<
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				figcaption?: Array<{
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?: 'normal'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
				}>
				_type: 'image'
				_key: string
		  }
	>
	publishDate?: string
	metadata?: Metadata
} | null

// Source: src/sanity/lib/queries.ts
// Variable: ALL_EXPERIENCES_QUERY
// Query: *[_type == 'experience'] | order(displayOrder asc){	_id,	title,	"slug": slug.current,	description,	image { asset->, alt },	"propertyIds": properties[]->._id}
export type ALL_EXPERIENCES_QUERY_RESULT = Array<{
	_id: string
	title: string | null
	slug: string | null
	description: string | null
	image: {
		asset: {
			_id: string
			_type: 'sanity.imageAsset'
			_createdAt: string
			_updatedAt: string
			_rev: string
			originalFilename?: string
			label?: string
			title?: string
			description?: string
			altText?: string
			sha1hash?: string
			extension?: string
			mimeType?: string
			size?: number
			assetId?: string
			uploadId?: string
			path?: string
			url?: string
			metadata?: SanityImageMetadata
			source?: SanityAssetSourceData
		} | null
		alt: string | null
	} | null
	propertyIds: Array<string> | null
}>

// Source: src/ui/modules/blog/blog-index/index.tsx
// Variable: BLOG_INDEX_QUERY
// Query: *[_type == 'blog.post']|order(publishDate desc){		...,		categories[]->,		author->{			name,			image{				...,				asset->			}		},		metadata{			...,			image{				...,				asset->			}		},		'slug': $blogDir + metadata.slug.current,	}
export type BLOG_INDEX_QUERY_RESULT = Array<{
	_id: string
	_type: 'blog.post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	content?: Array<
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				figcaption?: Array<{
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?: 'normal'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
				}>
				_type: 'image'
				_key: string
		  }
	>
	publishDate?: string
	metadata: {
		_type: 'metadata'
		title?: string
		description?: string
		slug?: Slug
		image: {
			asset: {
				_id: string
				_type: 'sanity.imageAsset'
				_createdAt: string
				_updatedAt: string
				_rev: string
				originalFilename?: string
				label?: string
				title?: string
				description?: string
				altText?: string
				sha1hash?: string
				extension?: string
				mimeType?: string
				size?: number
				assetId?: string
				uploadId?: string
				path?: string
				url?: string
				metadata?: SanityImageMetadata
				source?: SanityAssetSourceData
			} | null
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		} | null
		noIndex?: boolean
	} | null
	categories: null
	author: null
	slug: unknown
}>

// Source: src/ui/modules/blog/blog-post-list.tsx
// Variable: BLOG_POST_LIST_QUERY
// Query: *[_type == 'blog.post']|order(publishDate desc)[0...$limit]{		...,		categories[]->{			title,			slug		},		author->{			name,			image{				...,				asset->			}		},		metadata{			...,			image{				...,				asset->			}		},		'slug': $blogDir + metadata.slug.current,	}
export type BLOG_POST_LIST_QUERY_RESULT = Array<{
	_id: string
	_type: 'blog.post'
	_createdAt: string
	_updatedAt: string
	_rev: string
	title?: string
	content?: Array<
		| ({
				_key: string
		  } & Code)
		| ({
				_key: string
		  } & CustomHtml)
		| {
				children?: Array<{
					marks?: Array<string>
					text?: string
					_type: 'span'
					_key: string
				}>
				style?:
					| 'blockquote'
					| 'h1'
					| 'h2'
					| 'h3'
					| 'h4'
					| 'h5'
					| 'h6'
					| 'normal'
				listItem?: 'bullet' | 'number'
				markDefs?: Array<{
					href?: string
					_type: 'link'
					_key: string
				}>
				level?: number
				_type: 'block'
				_key: string
		  }
		| {
				asset?: SanityImageAssetReference
				media?: unknown
				hotspot?: SanityImageHotspot
				crop?: SanityImageCrop
				alt?: string
				figcaption?: Array<{
					children?: Array<{
						marks?: Array<string>
						text?: string
						_type: 'span'
						_key: string
					}>
					style?: 'normal'
					listItem?: 'bullet' | 'number'
					markDefs?: Array<{
						href?: string
						_type: 'link'
						_key: string
					}>
					level?: number
					_type: 'block'
					_key: string
				}>
				_type: 'image'
				_key: string
		  }
	>
	publishDate?: string
	metadata: {
		_type: 'metadata'
		title?: string
		description?: string
		slug?: Slug
		image: {
			asset: {
				_id: string
				_type: 'sanity.imageAsset'
				_createdAt: string
				_updatedAt: string
				_rev: string
				originalFilename?: string
				label?: string
				title?: string
				description?: string
				altText?: string
				sha1hash?: string
				extension?: string
				mimeType?: string
				size?: number
				assetId?: string
				uploadId?: string
				path?: string
				url?: string
				metadata?: SanityImageMetadata
				source?: SanityAssetSourceData
			} | null
			media?: unknown
			hotspot?: SanityImageHotspot
			crop?: SanityImageCrop
			_type: 'image'
		} | null
		noIndex?: boolean
	} | null
	categories: null
	author: null
	slug: unknown
}>

// Source: src/ui/modules/search/store.ts
// Variable: SEARCH_QUERY
// Query: *[	_type in $scope	&& defined(metadata.slug.current)	&& metadata.noIndex != true	&& !(metadata.slug.current in ['404'])	&& [		modules[].intro[].children[].text,		modules[].content[].children[].text,		content[].children[].text,		title,		metadata.title,		metadata.description	] match $queryMatch]{	_id,	_type,	title,	'slug': select(		_type == 'blog.post' => $blogDir + metadata.slug.current,		metadata.slug.current == 'index' => '/',		'/' + metadata.slug.current	)}
export type SEARCH_QUERY_RESULT = Array<{
	_id: string
	_type: 'blog.post'
	title: string | null
	slug: '/' | unknown
}>

declare module '@sanity/client' {
	interface SanityQueries {
		"*[_type == $type && metadata.slug.current == $slug][0]{\n\t'title': coalesce(metadata.title, title),\n}": OG_QUERY_RESULT
		"*[_type == 'blog.post' && metadata.slug.current == $slug][0]{\n\t...,\n\tcontent[]{\n\t\t...,\n\t\t_type == 'image' => {\n\t\t\t...,\n\t\t\tasset->\n\t\t}\n\t},\n\t'contentPlainText': pt::text(content),\n\t'readTime': length(string::split(pt::text(content), ' ')) / 200,\n\t'headings': content[style in ['h2', 'h3', 'h4', 'h5', 'h6']]{\n\t\tstyle,\n\t\t'text': pt::text(@)\n\t},\n\tcategories[]->{\n\t\ttitle,\n\t\tslug\n\t},\n\tauthor->{\n\t\tname,\n\t\timage{\n\t\t\t...,\n\t\t\tasset->\n\t\t}\n\t}\n}": BLOG_POST_QUERY_RESULT
		'{\n\t\'blog\': *[_type == \'site\'][0]{\n\t\t"metadata": {\n\t\t\t"title": coalesce(seo.metaTitle, title) + " Blog",\n\t\t\t"description": seo.metaDescription\n\t\t}\n\t},\n\t\'posts\': *[_type == \'blog.post\' && metadata.noIndex != true]|order(publishDate desc){\n\t\ttitle,\n\t\tcontent,\n\t\tpublishDate,\n\t\tmetadata\n\t}\n}': BLOG_RSS_QUERY_RESULT
		"*[_type == 'site' && _id == 'site'][0]": SITE_QUERY_RESULT
		"*[_type == 'homePage' && _id == 'homePage'][0]{\n\t...,\n\theroImage { asset->, alt },\n\tnavLabels[]{\n\t\t...,\n\t\ttarget->{ _type, \"slug\": slug.current }\n\t}\n}": HOME_PAGE_QUERY_RESULT
		"*[_type == 'ourHomesPage' && _id == 'ourHomesPage'][0]{\n\theroHeadline,\n\theroImage { asset->, alt },\n\tctaQuestion,\n\texperiencesCtaLabel,\n\tctaBackground { asset->, alt },\n\tseo\n}": OUR_HOMES_PAGE_QUERY_RESULT
		"*[_type == 'altWayPage' && _id == 'altWayPage'][0]{\n\t...,\n\theroBackground { asset->, alt },\n\tmissionImage { asset->, alt },\n\tmissionDecorImage { asset->, alt },\n\tvaluePropEditorialImage { asset->, alt },\n\tvaluePropEditorialDecorLeft { asset->, alt },\n\tvaluePropEditorialDecorRight { asset->, alt },\n\tvaluePropSecondaryImage { asset->, alt },\n\tpromiseBackground { asset->, alt },\n\tpromiseCTADecorLeft { asset->, alt },\n\tpromiseCTADecorRight { asset->, alt },\n\tbottomCTABackground { asset->, alt },\n\treviews[]->{\n\t\tguestName, rating, body, guestLocation, stayDate,\n\t\tguestPhoto { asset->, alt },\n\t\t\"propertyTitle\": property->title\n\t}\n}": ALT_WAY_PAGE_QUERY_RESULT
		"*[_type == 'experiencesPage' && _id == 'experiencesPage'][0]{\n\t...,\n\theroBackground { asset->, alt },\n\theroFlower { asset->, alt },\n\tdecorBasket { asset->, alt },\n\tdecorStars { asset->, alt },\n\tdecorDaisy { asset->, alt }\n}": EXPERIENCES_PAGE_QUERY_RESULT
		"*[_type == 'joinUsPage' && _id == 'joinUsPage'][0]{\n\t...,\n\theroImage { asset->, alt },\n\tpropertyImage { asset->, alt },\n\theroDecorFlower { asset-> },\n\tcontentDecorImage { asset-> },\n\tformDecorBg { asset-> }\n}": JOIN_US_PAGE_QUERY_RESULT
		"*[_type == 'contactPage' && _id == 'contactPage'][0]{\n\t...,\n\theroImage { asset->, alt },\n\tmobileHeroAsset { asset->, alt },\n\tbackgroundCloudAsset { asset->, alt },\n\tsideFlowerAsset { asset->, alt }\n}": CONTACT_PAGE_QUERY_RESULT
		"*[_type == 'legalPage' && slug.current == $slug][0]": LEGAL_PAGE_QUERY_RESULT
		"*[_type == 'legalPage' && defined(slug.current)].slug.current": ALL_LEGAL_PAGES_QUERY_RESULT
		"*[_type == 'property' && status != 'hidden'] | order(displayOrder asc){\n\t_id,\n\ttitle,\n\t\"slug\": slug.current,\n\ttagline,\n\tshortDescription,\n\tcardThumbnail { asset->, alt },\n\theroImage { asset->, alt },\n\tshowcaseSecondaryImage { asset->, alt },\n\tshowcaseDecorImage { asset->, alt },\n\tshowcaseDecorTop,\n\tshowcaseDecorRight,\n\tshowcaseDecorWidth,\n\tshowcaseDecorHeight,\n\tshowcaseDecorRotation,\n\tpullQuote,\n\tlocationHeadline,\n\tcardAmenities,\n\tpropertyType,\n\tpriceFrom,\n\tmaxGuests,\n\tbedrooms,\n\tbathrooms,\n\tstatus,\n\tdisplayOrder,\n\trentalwisePropertyId\n}": ALL_PROPERTIES_QUERY_RESULT
		'*[_type == \'property\' && slug.current == $slug][0]{\n\t...,\n\theroImage { asset->, alt },\n\tdetailCoverImage { asset->, alt },\n\tgallery[]{ asset->, alt },\n\tcardThumbnail { asset->, alt },\n\tamenities[]->{ name, icon },\n\tamenitiesSectionImage { asset->, alt },\n\texperiences[]->{\n\t\ttitle,\n\t\t"slug": slug.current,\n\t\tdescription,\n\t\timage { asset->, alt }\n\t},\n\texperiencesBgImage { asset->, alt, hotspot, crop },\n\thighlights[]{ title, body, image { asset->, alt }, secondaryImage { asset->, alt }, decorImage { asset-> } },\n\tcauseImages[]{ asset->, alt },\n\tctaBackground { asset->, alt },\n\tfaqs[]{ question, answer },\n\tlocation,\n\t"reviews": *[_type==\'review\' && references(^._id) && published==true] | order(stayDate desc) [0..20]{\n\t\tguestName, rating, body, guestLocation, stayDate,\n\t\tguestPhoto { asset->, alt },\n\t\t"propertyTitle": property->title\n\t}\n}': PROPERTY_QUERY_RESULT
		"*[_type == 'property' && defined(slug.current)].slug.current": ALL_PROPERTY_SLUGS_QUERY_RESULT
		"*[_type == 'blog.post'] | order(publishDate desc)": ALL_POSTS_QUERY_RESULT
		"*[_type == 'blog.post' && metadata.slug.current == $slug][0]": POST_BY_SLUG_QUERY_RESULT
		'*[_type == \'experience\'] | order(displayOrder asc){\n\t_id,\n\ttitle,\n\t"slug": slug.current,\n\tdescription,\n\timage { asset->, alt },\n\t"propertyIds": properties[]->._id\n}': ALL_EXPERIENCES_QUERY_RESULT
		"\n\t*[_type == 'blog.post']|order(publishDate desc){\n\t\t...,\n\t\tcategories[]->,\n\t\tauthor->{\n\t\t\tname,\n\t\t\timage{\n\t\t\t\t...,\n\t\t\t\tasset->\n\t\t\t}\n\t\t},\n\t\tmetadata{\n\t\t\t...,\n\t\t\timage{\n\t\t\t\t...,\n\t\t\t\tasset->\n\t\t\t}\n\t\t},\n\t\t'slug': $blogDir + metadata.slug.current,\n\t}\n": BLOG_INDEX_QUERY_RESULT
		"\n\t*[_type == 'blog.post']|order(publishDate desc)[0...$limit]{\n\t\t...,\n\t\tcategories[]->{\n\t\t\ttitle,\n\t\t\tslug\n\t\t},\n\t\tauthor->{\n\t\t\tname,\n\t\t\timage{\n\t\t\t\t...,\n\t\t\t\tasset->\n\t\t\t}\n\t\t},\n\t\tmetadata{\n\t\t\t...,\n\t\t\timage{\n\t\t\t\t...,\n\t\t\t\tasset->\n\t\t\t}\n\t\t},\n\t\t'slug': $blogDir + metadata.slug.current,\n\t}\n": BLOG_POST_LIST_QUERY_RESULT
		"*[\n\t_type in $scope\n\t&& defined(metadata.slug.current)\n\t&& metadata.noIndex != true\n\t&& !(metadata.slug.current in ['404'])\n\t&& [\n\t\tmodules[].intro[].children[].text,\n\t\tmodules[].content[].children[].text,\n\t\tcontent[].children[].text,\n\t\ttitle,\n\t\tmetadata.title,\n\t\tmetadata.description\n\t] match $queryMatch\n]{\n\t_id,\n\t_type,\n\ttitle,\n\t'slug': select(\n\t\t_type == 'blog.post' => $blogDir + metadata.slug.current,\n\t\tmetadata.slug.current == 'index' => '/',\n\t\t'/' + metadata.slug.current\n\t)\n}": SEARCH_QUERY_RESULT
	}
}
